### ISSUE TITLE
settings not saving unless manually added to settings.cfg (docker)

### ISSUE THREAD

**Issue by GOvEy1nw** [piejanssens/premiumizer#184]
Any settings that I've not manually added to the settings.cfg file aren't remembered once the docker is restarted.

Due to this, I've added the settings manually for my Premiumizer ID etc, as well as download location.

However, there isn't an 'automation' section in the settings.cfg, so they still get reset. Can these settings be added?

**Comment by neox387** [comment]
Those automation settings are under
[downloads] in the conf file. 

Your config file should have all the settings as in settings.cfg.tpl

Not sure with Docker with all the permission stuff... Mount /conf and premiumizer should be able to write to this permantly to save settings? @piejanssens

**Comment by FallingReign** [comment]
mounting :/premiumizer/conf should work. 

Here is the docker-compose that works for me:

```
premiumizer:
    image: piejanssens/premiumizer
    container_name: premiumizer
    restart: always
    volumes:
      - ${HOME}/docker/premiumizer:/premiumizer/conf
      - ${HOME}/docker/shared/blackhole:/blackhole
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
```
Note: you will need to adjust the indentation if you copy and paste this.
